# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Miguel MJ
credit:
    - lang: ~
      text: "This website is powered by [Jekyll](jekyllrb.com) and hosted by [GitHub Pages](pages.github.com). Its source code is available in my GitHub."
    - lang: "es"
      text: "Esta página esta hecha con [Jekyll](jekyllrb.com) y alojada en [GitHub Pages](pages.github.com). Su código fuente está disponible en mi GitHub."
description:
    - lang: ~
      text: "I'm a Computer Science student and programming is my passion. I love learning as much as I love teaching, sharing knowledge is a high human value!"
    - lang: "es"
      text: "Soy un estudiante de Ingeniería Informática apasionado por la programación. Aprender me gusta tanto como enseñar. ¡Compartir conocimiento es un gran valor humano!."

contactme:
    - lang: ~
      text: "Contact me"
    - lang: "es"
      text: "Contacto"
baseurl: "" # the subpath of your site, e.g. /blog
url: "MiguelMJ.github.io" # the base hostname & protocol for your site

    
collections:
    projects:
        output: true
    series:
        output: true

# Build settings
markdown: kramdown
